import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; 
import Footer from "./components/Footer";
// Define the fonts
const geistSans = Geist({
  variable: "--font-geist-sans", // Custom variable name for the font
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Custom variable name for the font
  subsets: ["latin"],
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Page description
};

// RootLayout component that wraps around the children
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Metadata can go here */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {children} {/* This will render the children components */}
        
      </body>
    </html>
  );
}
